### ISSUE TITLE
Test Task List

### ISSUE THREAD

**Issue by bohdanrutylo** [gemberge/zabavy#1]
- [x] a task list item
- [x] list syntax required
- [x] normal **formatting**, @mentions, #1234 refs
- [x] incomplete
- [x] completed
